src/Entity/Game.php
<?php

namespace App\Entity;

use App\Repository\GameRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=GameRepository::class)
 */
class Game
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="datetime")
     */
    private $date;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $fiveLink;

    /**
     * @ORM\ManyToMany(targetEntity=User::class, inversedBy="games")
     */
    private $user;

    /**
     * @ORM\OneToMany(targetEntity=Statistique::class, mappedBy="game")
     */
    private $statistiques;

    /**
     * @ORM\Column(type="boolean")
     */
    private $isVisible = true;

    public function __construct()
    {
        $this->user = new ArrayCollection();
        $this->statistiques = new ArrayCollection();
        $this->date = new \DateTime('now');
    }

    public function getDateGame(): string
    {
        return $this->getDate()->format('d-m-Y');
    }


    public function getId(): ?int
    {
        return $this->id;
    }

    public function getDate(): ?\DateTimeInterface
    {
        return $this->date;
    }

    public function setDate(\DateTimeInterface $date): self
    {
        $this->date = $date;

        return $this;
    }

    public function getFiveLink(): ?string
    {
        return $this->fiveLink;
    }

    public function setFiveLink(?string $fiveLink): self
    {
        $this->fiveLink = $fiveLink;

        return $this;
    }

    /**
     * @return Collection|User[]
     */
    public function getUser(): Collection
    {
        return $this->user;
    }

    public function addUser(User $user): self
    {
        if (!$this->user->contains($user)) {
            $this->user[] = $user;
        }

        return $this;
    }

    public function removeUser(User $user): self
    {
        $this->user->removeElement($user);

        return $this;
    }

    /**
     * @return Collection|Statistique[]
     */
    public function getStatistiques(): Collection
    {
        return $this->statistiques;
    }

    public function addStatistique(Statistique $statistique): self
    {
        if (!$this->statistiques->contains($statistique)) {
            $this->statistiques[] = $statistique;
            $statistique->setGame($this);
        }

        return $this;
    }

    public function removeStatistique(Statistique $statistique): self
    {
        if ($this->statistiques->removeElement($statistique)) {
            // set the owning side to null (unless already changed)
            if ($statistique->getGame() === $this) {
                $statistique->setGame(null);
            }
        }

        return $this;
    }

    public function getIsVisible(): ?bool
    {
        return $this->isVisible;
    }

    public function setIsVisible(bool $isVisible): self
    {
        $this->isVisible = $isVisible;

        return $this;
    }
}

src/Entity/Statistique.php
<?php

namespace App\Entity;

use App\Repository\StatistiqueRepository;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=StatistiqueRepository::class)
 */
class Statistique
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="integer", nullable=true)
     */
    private $passesDecisives = 0;

    /**
     * @ORM\Column(type="integer", nullable=true)
     */
    private $buts = 0;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $resultat = '-';

    /**
     * @ORM\ManyToOne(targetEntity=User::class, inversedBy="statistiques")
     */
    private $user;

    /**
     * @ORM\ManyToOne(targetEntity=Game::class, inversedBy="statistiques")
     */
    private $game;


    public function getId(): ?int
    {
        return $this->id;
    }

    public function getGameByDateOrder(): ?Game
    {
        return $game;
    }


    public function countButsByGameByPLayer() : array
    {
        $buts = [];
        foreach ($this->getStatistiques() as $statistique) {
            $buts[] = $statistique->getButs();
        }
        dump($buts);
        return $buts;
    }


    public function getPassesDecisives(): ?int
    {
        return $this->passesDecisives;
    }

    public function setPassesDecisives(?int $passesDecisives): self
    {
        $this->passesDecisives = $passesDecisives;

        return $this;
    }

    public function getButs(): ?int
    {
        return $this->buts;
    }

    public function setButs(?int $buts): self
    {
        $this->buts = $buts;

        return $this;
    }

    public function getResultat(): ?string
    {
        return $this->resultat;
    }

    public function setResultat(string $resultat): self
    {
        $this->resultat = $resultat;

        return $this;
    }

    public function getUser(): ?User
    {
        return $this->user;
    }

    public function setUser(?User $user): self
    {
        $this->user = $user;

        return $this;
    }

    public function getGame(): ?Game
    {
        return $this->game;
    }

    public function setGame(?Game $game): self
    {
        $this->game = $game;

        return $this;
    }
}

templates/statistiques/_deleteStats.html.twig
<form  method="post" action="{{ path('admin_delete_stats_player', { 'gameId': game.id, 'userId': user.id, 'statistiqueId' : statistique.id }) }}" class="text-light" onsubmit="return confirm('Attention !!! Vous allez supprimer les statistiques de ce joueur. Confirmez-vous la suppression ?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ statistique.id) }}">
    <button class="btn text-danger border-danger fs-4 mt-4">Supprimer ces stats<i class="text-danger ps-3 fas fa-trash-alt"></i></button>
</form>

templates/statistiques/_editStats.html.twig
{% extends 'base.html.twig' %}

{% block title %}Modifier les statistiques {% endblock %}
{% form_theme form 'bootstrap_5_layout.html.twig' %}


{% block body %}
    <div class="new-game">
        <div class='container-fluid text-white text-center pt-5'>
            <h1 class="mt-2 text-light text-center pb-3 m-5 border-bottom border-primary border-3 fs-1">Modifier les statistiques de <span class="text-danger">{{ user.pseudo }}</span> pour le match du <span class="text-danger">{{ game.dateGame }}</span></h1>
            {{ include('statistiques/_form.html.twig', {'button_label': 'Mettre à jour ces statistiques'}) }}
            <div>{{ include('statistiques/_deleteStats.html.twig') }}</div>
            <div class="mt-4">
                <a class="text-light" href="{{ path('admin_show_players_game', { id: game.id }) }}">Retour à la liste des joueurs du match</a>
            </div>
        </div>
    </div>
{% endblock %}

templates/statistiques/_form.html.twig
{{ form_start(form) }}
    <div class="w-25 fs-2 mx-auto">{{ form_widget(form) }}</div>
    <button class="btn text-white text-center border-white fs-2 mt-4">{{ button_label|default('Sauvegarder')}}</button>
{{ form_end(form) }}

templates/statistiques/showGames.html.twig
{% extends 'base.html.twig' %}

{% block title %}Liste des matchs{% endblock %}

{% block body %}
    <div class="playerList container-fluid">
        <h1 class="mt-5 text-light text-center pb-3 m-5 border-bottom border-primary border-3 fs-1">Sélectionner un match</h1>
        <table class="d-flex justify-content-center fs-2">
            <tr class="text-primary border-bottom border-primary">
                <th class="pe-3 py-2">Match</th>
                <th class="pe-3">Voir</th>
            </tr>
            {% for game in games %}
                <tr class="bg-dark text-light border-bottom border-secondary fs-5">
                    <td class="w-50 pe-4 fs-4 py-2">{{ game.dateGame }}</td>
                    <td class="w-50 pe-2 text-center">
                        <a class="text-warning" href="{{ path('admin_show_players_game', {'id': game.id}) }}"><i class="fas fa-eye"></i></a>
                    </td>
                </tr>
            {% endfor %}
        </table>
        <p class="mt-5 text-center">

        </p>
    </div>

{% endblock %}

templates/statistiques/showPlayersInGames.html.twig
{% extends 'base.html.twig' %}

{% block title %}Liste des joueurs{% endblock %}

{% block body %}

    <div class="playerList container-fluid">
        <h1 class="mt-5 text-light text-center pb-3 m-5 border-bottom border-primary border-3 fs-1">Modifier les statistiques du match du <span class="text-danger">{{ game.dateGame }}</span></h1>
        <table class="d-flex justify-content-center fs-2">
            <tr class="text-primary border-bottom border-primary">
                <th class="pe-3 py-2">Joueur</th>
                <th class="pe-3">PD</th>
                <th class="pe-3">Buts</th>
                <th class="pe-3">Résultat</th>
                <th class="pe-3">Modifier</th>
            </tr>
            {% for statistique in statistiques %}
            <tr class="bg-dark text-light border-bottom border-secondary fs-3">
                <td class="w-50 pe-4 fs-4 py-2">{{ statistique.user.pseudo }}</td>
                <td class="w-50 pe-4 fs-4 py-2">{{ statistique.buts }}</td>
                <td class="w-50 pe-4 fs-4 py-2">{{ statistique.passesDecisives }}</td>
                <td class="w-50 pe-4 fs-4 py-2">{{ statistique.resultat }}</td>
                <td class="w-50 pe-2 text-center">
                    <a class="text-warning" href="{{ path('admin_edit_stats_player', {'gameId': statistique.game.id, 'userId' : statistique.user.id, 'statistiqueId': statistique.id }) }}"><i class="fas fa-user-edit"></i></a>
                </td>
            </tr>
            {% endfor %}
        </table>
    </div>

{% endblock %}

templates/statistiques/showStatsByGameByPlayer.html.twig
{# {% extends 'base.html.twig' %}

{% block title %}Liste des joueurs{% endblock %}

{% block body %}
    <div class="playerList container-fluid">
        <h1 class="mt-5 text-light text-center pb-3 m-5 border-bottom border-primary border-3 fs-1">Statistiques de <span class="text-danger">{{ user.pseudo }}</span> du <span class="text-danger"> {{ game.dateGame }}</span></h1>
        <table class="d-flex justify-content-center fs-2">

            <tr class="text-primary border-bottom border-primary">
                <th class="pe-3 py-2">Joueur</th>
                <th class="pe-3 py-2">Buts</th>
                <th class="pe-3 py-2">PD</th>
                <th class="pe-3 py-2">Resultat</th>
                <th class="pe-3">Modifier</th>
            </tr>
            <tr class="bg-dark text-light border-bottom border-secondary fs-3">
                 <td class="w-50 pe-4 fs-4 py-2">{{ user.pseudo}}</td>
                 <td class="w-50 pe-2 text-center">{{ statistique.buts }}</td>
                 <td class="w-50 pe-2 text-center">{{ statistique.passesDecisives }}</td>
                 <td class="w-50 pe-2 text-center">{{ statistique.resultat }}</td>
                <td class="w-50 pe-2 text-center">
                    <a href="{{ path('admin_edit_stats_player', { 'gameId': game.id, 'userId': user.id, 'statistiqueId' : statistique.id }) }}"> <i class="fas fa-user-edit"></i></a>
                </td>
            </tr>
        </table>
        <p class="mt-5 text-center">

        </p>
    </div>
{% endblock %}